---
title: "ib_others"
author: "Luis Armando Figueroa"
date: '2022-10-02'
output:
  pdf_document: default
---

```{r packages, include=FALSE}
library(metafor)
library(openxlsx)
library(forestplot)
library(dplyr)
```

```{r cleaning of Continous outcome, include=FALSE}
data <- read.xlsx("Data extraction cleaned.xlsx", sheet = 3)
data2 <- read.xlsx("Data extraction cleaned.xlsx", sheet = 4)
View(data)
View(data2)
# Delete 
cont1 <- data[-c(1,2,3,4),-c(7,19,20,21)]
rownames(cont1) <- NULL #Restablecer el numero de filas
# Extraer continous data from dichotomus data
cont2 <- data2[c(36,38, 40), -7]
rownames(cont2) <- NULL

# Renamecols, RefID = id, Intervention = int, Intervention.Dose = intd, 
# Comparison.(bupivacaine,.placebo,.other) = comp, Comparison.Dose = cd, 
# Outcomes = outc, Total.participants.(n) = tpar, Total.Intervention.(n) = tiint, 
# Total.comparator(n) = tcomp, SD = sd, IQR = iqr, mean.1 = mean1, SD.1 = sd1, 
# median.1 = median1, IQR.1 = iqr1, p-value = pvalue
names(cont1) <- c('id', 'int', 'intd', 'comp', 'compd', 'outc', 'tpart', 'tint', 
                  'tcomp', 'mean', 'sd', 'median', 'iqr', 'mean1', 'sd1', 'median1', 
                  'iqr1', 'pvalue')
# Renombrar cont2, RefID = id, Intervention = int, Intervention.Dose = intd, 
# Comparison = comp, Comparison.Dose = compd, Outcomes:.adverse.effects = outc, 
# Total.participants.(n) = tpart, Total.Intervention.(n) = tint, Total.comparator(n) = tcomp,
# n = mean, SD = sd, n.1 = mean1, SD.1 = sd1, Mean.difference = median, 95%.CI.LL = iqr
# 95%.CI.UL = iqr1, p-value = pvalue
names(cont2)
names(cont2) <- c('id', 'int', 'intd', 'comp', 'compd', 'outc', 'tpart', 'tint', 
                  'tcomp', 'mean', 'sd', 'mean1', 'sd1', 'median', 'iqr','iqr1',
                  'pvalue')

# Add a col with median value
cont2 <- cbind(cont2, median1=c(NA, NA, NA))

# Complete total participants with tint + tcomp
cont1$tpart <- cont1$tint + cont1$tcomp
cont2$tpart <- cont2$tint + cont2$tcomp

# Dejar variables a una sola unidad
table(cont1$intd) #Buscando fusionar o eliminar filas
cont1$intd[cont1$intd == '199 mg'] <- '199'
cont1$intd[cont1$intd == '266 mg'] <- '266'
cont1$intd[cont1$intd == '300 mg'] <- '300'
cont1$intd[cont1$intd == '66 mg'] <- '66'
table(cont1$intd)

table(cont2$intd)
cont2$intd[cont2$intd == '300 mg'] <- '300'
table(cont2$intd)

# Fusionar distintos placebo como un unico placebo general
table(cont1$comp)
cont1$comp[cont1$comp == 'placebo cream'] <- 'placebo'
cont1$comp[cont1$comp == 'placebo (0.9% sodium chloride)'] <- 'placebo'
table(cont1$comp)

rownames(cont1) <- NULL
cont1[is.na(cont1$tpart), ] #visualizar NA filas
cont1 <- cont1[-c(46,47,48),] 
rownames(cont1)

# Checar cada variable 
table(cont1$mean, useNA = "ifany") #visualizar NA filas
table(cont1$sd, useNA = "ifany")
table(cont1$mean1, useNA = "ifany")
table(cont1$sd1, useNA = "ifany")
table(cont1$iqr, useNA = "ifany")
cont1$iqr[cont1$iqr == '12--5760'] <- '12-5760'
cont1$iqr[cont1$iqr == '6--5760 '] <- '6-5760'
table(cont1$iqr, useNA = "ifany")
table(cont1$iqr1, useNA = "ifany")
cont1$iqr1[cont1$iqr1 == '18- 5760'] <- '18 - 5760'
table(cont1$iqr1, useNA = "ifany")

# convertir a variables numericas
str(cont1)
cont1$intd <- as.numeric(cont1$intd) 
# cont1$mean <- as.numeric(cont1$mean) 
# cont1$sd <- as.numeric(cont1$sd)
# cont1$iqr <- as.numeric(cont1$iqr)
# cont1$mean1 <- as.numeric(cont1$mean1) 
# cont1$sd1 <- as.numeric(cont1$sd1)
# cont1$iqr1 <- as.numeric(cont1$iqr1)
# cont1$pvalue <- as.numeric(cont1$pvalue)

str(cont2)
# cont2$intd <- as.numeric(cont2$intd)
# cont2$mean <- as.numeric(cont2$mean) 
# cont2$sd <- as.numeric(cont2$sd)
# cont2$mean1 <- as.numeric(cont2$mean1) 
# cont2$sd1 <- as.numeric(cont2$sd1)
# cont2$pvalue <- as.numeric(cont2$pvalue)
# cont2$median1 <- as.numeric(cont2$median1) 
str(cont2)

# Eliminar si no hay mean & sd, sd & iqr
cont1[is.na(cont1$mean) & is.na(cont1$median),]
cont1[is.na(cont1$sd) & is.na(cont1$iqr),]
cont1 <- cont1[-c(2,5, 7, 8:10, 12:15, 17:25, 29:34, 44,45), ]
rownames(cont1) <- NULL
cont1[is.na(cont1$mean1) & is.na(cont1$median1),]
cont1[is.na(cont1$sd1) & is.na(cont1$iqr1),]

```

```{r analysis outcomes, include=FALSE}
# Agrupar outcomes -> Time to First Opioid  
datac_tfp <- cont1[c(4,5,6), ]
datac_tfp

dat_tfp <- escalc(measure="MD", 
               m1i=mean_post1, m2i = mean_post2, 
               sd1i  = sd_post1, sd2i = sd_post2, 
               n1i = n1, n2i= n2, data=database)
```



```{r cleaning of Dichotomus outcomes, include=FALSE}
data2 <- read.xlsx("Data extraction cleaned.xlsx", sheet = 4)
View(data2)

# Eliminamos los que tenian pre-operatorio diferente y datos no dicotomicos
colnames(data2)
dic1 <- data2[-c(1,2,36,38,40), -c(7,12,14,15,16,17,18)] 
rownames(dic1) <- NULL

# Renamecols, RefID = id, Intervention = int, Intervention.Dose = intd, 
# Comparison = comp, Comparison.Dose = cd, Outcomes:.adverse.effects = outc, 
# Total.participants.(n) = tpart, Total.Intervention.(n) = n1, 
# Total.comparator(n) = n2, n = e1, n = e2
names(dic1) <- c('id', 'int', 'intd', 'comp', 'compd', 'outc', 'tpart', 'n1', 
                  'n2', 'e1', 'e2')

# Complete total participants with tint + tcomp
dic1$tpart <- dic1$n1 + dic1$n2

# Dosis de intervencion en una sola unidad
table(dic1$intd)
dic1$intd[dic1$intd == '199 mg'] <- '199'
dic1$intd[dic1$intd == '266 mg'] <- '266'
dic1$intd[dic1$intd == '300 mg'] <- '300'
dic1$intd[dic1$intd == '66 mg'] <- '66'
table(dic1$intd)

# Fusionar distintos placebo como un unico placebo general
table(dic1$comp) # Preguntar si ponemos como multimodal al lb + aloe vera
dic1$comp[dic1$comp == 'placebo cream'] <- 'placebo'
dic1$comp[dic1$comp == 'placebo (0.9% sodium chloride)'] <- 'placebo'
table(dic1$comp)

# Convert to numeric variables
str(dic1)
dic1$intd <- as.numeric(dic1$intd)
dic1$e1 <- as.numeric(dic1$e1)
dic1$e2 <- as.numeric(dic1$e2)
str(dic1)

# Mas de dos efectos adversos <- agrupar outcomes 
datad_2ae <- dic1[c(1,8,15,22),]
datad_2ae

# Nausea/vomitos  <- agrupar outcomes
datad_vn <- dic1[c(11, 18, 25, 29, 31, 5, 12, 19, 26, 37), ]
datad_vn

# rescate de medicacion se elimina porque solo hay un articulo
# others advers effects <- agrupar outcomes

```

# Dichotomus outcome_Adverse effects_Metaanalisis 

```{r or_dichotomus outcomes_adverse effects, include=FALSE}
# 2 Adversse effects
dat_2ae <- escalc(measure="OR", ai=n1, bi=n2,
              ci=e1, di=e2, data=datad_2ae)
dat_2ae <- summary(dat_2ae)
dat_2ae
```

```{r meta_dichotomus outcomes_adverse effects, include=FALSE}
# 2 Adversse effects
meta_dat2ae_reml <- rma(yi, vi, method="REML", data=dat_2ae, test='knha')
meta_dat2ae_reml

```

```{r predict_dichotomus outcomes_adverse effects, include=FALSE}
# 2 Adversse effects
meta_2ae <- predict(meta_dat2ae_reml, transf = exp, digits = 2)
meta_2ae

```